export default [
  {Id: Math.random(), Reposo: true, IdSiniestro: "4230023", Nombre: "Martina Silva Herrera", Rut: "10645339-4", Tipo: "Trayecto", PrestacionesEconomicas: true, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
  {Id: Math.random(), Reposo: false, IdSiniestro: "4230023", Nombre: "Martina Silva Herrera", Rut: "10615339-4", Tipo: "Accidente trabajo", PrestacionesEconomicas: true, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
  {Id: Math.random(), Reposo: true, IdSiniestro: "4230023", Nombre: "Martina Silva Herrera", Rut: "10642339-4", Tipo: "Trayecto", PrestacionesEconomicas: false, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
  {Id: Math.random(), Reposo: true, IdSiniestro: "4230023", Nombre: "Martina Silva Herrera", Rut: "1064539-4", Tipo: "Trayecto", PrestacionesEconomicas: true, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
  {Id: Math.random(), Reposo: false, IdSiniestro: "4230023", Nombre: "Martina Silva Herrera", Rut: "10644959-4", Tipo: "Trayecto", PrestacionesEconomicas: false, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
  {Id: Math.random(), Reposo: true, IdSiniestro: "4230023", Nombre: "Martina Silva Herrera", Rut: "21645339-4", Tipo: "Enfermedad profesional", PrestacionesEconomicas: true, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
  {Id: Math.random(), Reposo: true, IdSiniestro: "4231230023", Nombre: "Martina Silva Herrera", Rut: "21645339-4", Tipo: "Enfermedad profesional", PrestacionesEconomicas: true, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
  {Id: Math.random(), Reposo: true, IdSiniestro: "4230023999", Nombre: "Martina Silva Herrera", Rut: "21645339-4", Tipo: "Enfermedad profesional", PrestacionesEconomicas: true, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
  {Id: Math.random(), Reposo: true, IdSiniestro: "423", Nombre: "Martina Silva Herrera", Rut: "21645339-4", Tipo: "Enfermedad profesional", PrestacionesEconomicas: true, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
  {Id: Math.random(), Reposo: true, IdSiniestro: "12230023", Nombre: "Martina Silva Herrera", Rut: "21645339-4", Tipo: "Enfermedad profesional", PrestacionesEconomicas: true, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
  {Id: Math.random(), Reposo: true, IdSiniestro: "423077023", Nombre: "Martina Silva Herrera", Rut: "21645339-4", Tipo: "Enfermedad profesional", PrestacionesEconomicas: true, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
  {Id: Math.random(), Reposo: true, IdSiniestro: "42308023", Nombre: "Martina Silva Herrera", Rut: "21645339-4", Tipo: "Enfermedad profesional", PrestacionesEconomicas: true, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
  {Id: Math.random(), Reposo: true, IdSiniestro: "884230023", Nombre: "Martina Silva Herrera", Rut: "21645339-4", Tipo: "Enfermedad profesional", PrestacionesEconomicas: true, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
  {Id: Math.random(), Reposo: true, IdSiniestro: "42323889", Nombre: "Martina Silva Herrera", Rut: "21645339-4", Tipo: "Enfermedad profesional", PrestacionesEconomicas: true, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
  {Id: Math.random(), Reposo: true, IdSiniestro: "42238898", Nombre: "Martina Silva Herrera", Rut: "21645339-4", Tipo: "Enfermedad profesional", PrestacionesEconomicas: true, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
  {Id: Math.random(), Reposo: true, IdSiniestro: "455230023", Nombre: "Martina Silva Herrera", Rut: "21645339-4", Tipo: "Enfermedad profesional", PrestacionesEconomicas: true, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
  {Id: Math.random(), Reposo: true, IdSiniestro: "6630023", Nombre: "Martina Silva Herrera", Rut: "21645339-4", Tipo: "Enfermedad profesional", PrestacionesEconomicas: true, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
  {Id: Math.random(), Reposo: true, IdSiniestro: "666023", Nombre: "Martina Silva Herrera", Rut: "21645339-4", Tipo: "Enfermedad profesional", PrestacionesEconomicas: true, FechaPresentacion: new Date().toLocaleDateString(), FechaSiniestro: new Date().toLocaleDateString(),
    Sucursal: "Santiago Centro", Cobertura: "Aplica", NumeroReposos: "4", Mecanismo: null, DiasSiniestro: 140, DiasImputables: 100, Rebajas: 40,
  },
]